* ulerm：统一的 Linux 环境仓库管理器（待完成）

*（此项目正在施工中，敬请期待）*

** 简介
此项目非常适合在此基础上进行更多配置，以搭配出自己的工作环境。
** 设计思想
Linux 从安装到配置的完整步骤，可以分为这样几个层次：
- 存储启动层：硬盘分区、文件系统、fstab、bootloader 等
- 用户层：用户与组（包括 sudo 权限）、家目录
- 基层：基本包管理器、声卡、显卡、网卡、触控板、触摸屏、蓝牙等
- 应用层：图形环境、浏览器、编辑器、终端模拟器等

而 ulerm 的作用就是，在已经完成存储启动层以及用户层的前提下，帮你快速完成基层，并且使用 uccr 帮你快速完成应用层，从而获得一个完整的系统工作环境。

并且，ulerm 本身与 uccr 都是可以备份与迁移的，这决定了 ulerm 适用于快速部署与长期维护。

** 什么是 uccr？
uccr 即 ulerm 兼容的配置仓库（Ulerm-Compatible Configuration Repo）。

uccr 从技术上来说，必须满足两个条件：
- 在根目录下提供名为“uccr-sync”的同步脚本。
- 此同步脚本是幂等的。
Technically, an uccr must meet 2 requirements:
- Provide a sync script with filename "uccr-sync".
- The sync script must be idempotent.

举个例子：dotbot 刚好就符合幂等的特性，因此将使用 dotbot 进行管理的配置仓库转变为 uccr 是非常简单的，例如将 [[https://github.com/Jguer/dotfiles][Jguer/dotfiles]] 转变为 uccr 只需要将 =install= 重名命为 =ulerm-sync= 。

所以，这里有一个问题：为什么不直接使用 dotbot，而是将它变为 uccr 以配合 ulerm 再使用呢？
换句话说，ulerm 提供了什么额外的好处？
这里列举如下：
- ulerm 提供了一个统一规范（文档正在编写）的基本设置流程，并将相关信息保存在 .coreset 下，可供 uccr 读取。这些基本设置包括语言环境、硬件预设等。
  - 当一个 uccr 检测到用户采用了 zh_CN 作为语言环境，则它可以安装 zh_CN 相关的字体、输入法等（如果是不支持的语言，可以统一回退到 en_US）。
  - 当一个 uccr 检测到用户采用了 networkmanager 作为网络预设，则它可以安装配置 networkmanager 的 applet。
  - 若一个 hyprland 的 uccr 检测到用户使用了 nvidia 的显卡预设，它可以安装 hyprland-nvidia 而不是原版的 hyprland。
- ulerm 提供了一个快速下载 uccr 的途径。
  - ulerm 官方提供的 uccr 是可以在引导流程中输入数字选项选择的。
  - 假如有一个第三方的 uccr 位于 https://github.com/foo/myuccr ，则可以在流程中为 uccr 选择 c-github，并为 uccr-id 填写 foo/myuccr（也可以 ~./ulerm --uccr c-github --uccr-id foo/myuccr~ ）。
  - 假如有一个第三方的 uccr 需要通过 ssh 访问私人服务器下载，则可以将 uccr 指定为 c-any，并将 uccr-id 指定为一个用以下载此 uccr 到 =../uccr= 的命令或脚本。
- ulerm 统一了使用 uccr 的前置条件。
  - 一般来说，很多配置仓库各有各的前置条件，而 ulerm 的规范统一化使得一台电脑上只要具有一个具有 sudo 权限的普通用户就足够利用 uccr 快速配置好余下的环境。

** 特性
- 可选择多种语言环境！
  - 不仅是单纯的选择语言，还包括字体、输入法、输入辅助、安装引导等。
  - 目前仅支持简体中文与英文，但本项目在设计上是可以轻松添加更多语言的。
- 很好上手！
  - 要求很低，只有两点：Linux 以及一个非 root 的 sudo 用户。
  - 安装脚本是幂等的。
  - (WIP) 引导非常详尽。
- 适合长期使用！
  - 本项目借助 git 与 [[https://github.com/anishathalye/dotbot][dotbot]] ，能够管理一切配置，包括你自己的，比如 Emacs 的 =~/.emacs.d= 。
  - 这使得长期维护与备份恢复、快速部署等变得轻松简单。
- 图形环境：[[https://github.com/swaywm][swaywm]]
- 输入法：[[https://github.com/fcitx/fcitx5][fcitx5]], [[https://github.com/rime][rime]]
- Shell：[[https://zsh.sourceforge.io][zsh]], [[https://github.com/ohmyzsh/ohmyzsh][ohmyzsh]], [[https://github.com/romkatv/powerlevel10k][p10k]]
- 终端：[[https://github.com/alacritty/alacritty][alacritty]]
- 屏幕亮度：[[https://github.com/FedeDP/Clightd][Clightd]]

** 快速上手
*** 安装
首先确保你已经安装了 Linux 并建立了一个具有 sudo 权限的普通用户，以此用户身份登录，运行：
#+begin_src bash
sudo pacman -Sy --needed git
git clone https://github.com/clsty/generic-archsway ~/confrepo
#+end_src
- 在支持中文显示的环境下，运行：
#+begin_src bash
~/confrepo/ulerm
#+end_src
- 在不支持中文显示的环境（如 tty 下，或者没装中文字体），运行：
#+begin_src bash
~/confrepo/ulerm -a
#+end_src
这样就完成了（可能需要重启系统）。

#+begin_quote
注：此脚本的行为是，首次安装时会提示选择什么语言，以及是否覆盖文件。之后每次运行均不再询问，除非删除 =.coreset= 。
#+end_quote

*** 开始使用
登录到 tty1（或登录到其它 tty 并手动运行命令 =~/.local/bin/wrp-sway= ），进入图形环境。
按 =Super+Return= （就是“windows 键”与“回车键”）来启动一个终端。
按 =Super+d= 来启动其他应用程序。
- 注意左 Ctrl 键和大写锁定键已互换（可使用 =~/.config/sway/config.d/config.conf= 修改）。
- 如果你还不会 vim 的基本操作，现在请输入 =sudo pacman -S --needed vim;vimtutor= 进行学习（至少完成第一讲）。

之后，运行 =vifm ~/.config/sway/config.d= 来查看并自定义 sway 的配置，尤其是 =config-keybind.conf= 。

*** 长期使用
非常推荐的是，当你进行了一些自定义配置（无论是否是 sway 相关的）时，都将它们保存到 =~/confrepo= 并且在那里管理它们。

#+begin_quote
比如，当你编辑或创建了某些配置文件在目录 =~/.config/something= 下，那么：
- 将此目录复制到 =~/confrepo= 下的某个合适的位置，比如 =~/confrepo/something= 。
- 编辑 =~/confrepo/ulerm.conf.yaml= 并在 =- link:= 部分下面添加对应的一行：
#+begin_src yaml
- link:
    ...
    ...
    ~/.config/something: something
    ...
    ...
#+end_src
显然，左边的是原路径，而右边的是 =~/confrepo= 下的相对路径。

单文件是完全同理的，比如你编辑或创建了某个配置文件 =~/.local/share/abc/foo/settings.conf= ，那么：
- 将此文件复制到 =~/confrepo= 下的某个合适的位置，比如 =~/confrepo/foo/settings.conf= 。
- 编辑 =~/confrepo/ulerm.conf.yaml= 并在 =- link:= 部分下面添加对应的一行：
#+begin_src yaml
- link:
    ...
    ...
    ~/.local/share/abc/foo/settings.conf: foo/settings.conf
    ...
    ...
#+end_src

之后，运行 =~/confrepo/ulerm= ，
它会根据 =~/confrepo/ulerm.conf.yaml= 下的 =- links:= 
删除原路径的文件或目录，
并在这些位置创建符号链接
（来源是 =~/confrepo= 下的对应文件及目录）。
#+end_quote

注意 =~/confrepo= 实际上是一个 git 仓库（且其中包含了一些子模块），所以你可以使用 git 来管理它，比如存档备份、上传到 GitHub 来分享、发送到其它设备上以快速部署、回溯历史记录，等等。

为了进行更多自定义，你可以查阅此项目所用到的其它项目的 wiki、指南、手册等，尤其是：
- [[https://wiki.archlinux.org/title/Sway][Sway - ArchWiki]]
- [[https://github.com/swaywm/sway/wiki][Sway User wiki]]
- [[https://missing-semester-cn.github.io/2020/version-control][Git - 计算机教育中缺失的一课]]
- [[https://github.com/anishathalye/dotbot][dotbot]]

** 使用技巧与建议
见 [[TipsAndTricks.zh_CN.org][使用技巧与建议]]。

** 贡献
欢迎参与贡献。
你可以创建 [[https://github.com/clsty/generic-archsway/pulls][Pull Requests]]，[[https://github.com/clsty/generic-archsway/issues][issues]] 等。

当前需要帮助的：
- 本地化（添加更多语言环境，完善已有环境）。
- 反馈与建议。
- 其他完善与提升。

** 致谢
感谢与此项目相关的所有自由开源项目。
- 此项目原本基于 [[https://github.com/Jguer/dotfiles][Jguer/dotfiles]] 。
- Fontconfig 原本基于 [[https://github.com/rydesun/dotfiles][rydesun/dotfiles]]
感谢此项目的所有贡献者。

** 许可
此项目以 GNU GPL v3.0 License 发布。
